# Generated by Django 5.1.3 on 2024-11-27 07:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_name', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('Rating', models.IntegerField(choices=[(4, '4'), (2, '2'), (5, '5'), (1, '1'), (3, '3')])),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musicians.musician_model')),
            ],
        ),
    ]
